# Site settings
title: "Jiaxu Liu's Homepage"
description: "Jiaxu Liu's Homepage"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jiaxu Liu"
resume_title:                   "undergraduate @ ANU & SDU"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jiaxu.liu@ieee.org"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+61 451873040"
resume_contact_address:         "26 Barry Dr, Lena Karmel"

resume_header_contact_info:     "26 Barry Dr, Lena Karmel • 0451873040 • jiaxu.liu@anu.edu.au"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hey there! I’m an undergraduate student at Australian National University pursuing a Bachelor’s degree in Advanced Computing (honour), prior to commencing the double degree program, I was doing Bachelor of Computer Science at Shandong University in China. I regard myself as (tap to expand):</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_links:           true
resume_section_papers:        true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/ljxw88"
#  resume_twitter_url:           "http://twitter.com/jglovier"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jiaxu-liu-a000b619a/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://ljxw88.github.io/"
#  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
